owner: kodo-in # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Payouts UI
    url: https://app.kodo.in
  - name: Payouts API
    url: https://api.kodo.in/health
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: P2P UI
    url: https://app.kodo.com
  - name: P2P Identity API
    url: https://api.kodo.com/identity/health
  - name: P2P form API
    url: https://api.kodo.com/form/health

status-website:
  cname: upptime.kodo.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kodo Upptime
  introTitle: "**Upptime** for Kodo application & services"
  navbar:
    - title: Status
      href: /
